/**
 * Export gameplay tuning + content for the Unity fork.
 * Run: npm run export:unity
 * Output: export/unity-snapshot/
 */
import { execSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { ORBITAL_CONFIG } from '../src/orbital/config.ts';
import { SKY_PALETTES } from '../src/orbital/skyPalettes.ts';
import { PHASE_LABELS } from '../src/orbital/types.ts';
import type { Locale } from '../src/i18n/locale.ts';
import { getLogCopy } from '../src/i18n/logContent.ts';
import { TEXT_LOGS } from '../src/narrative/logs.ts';
import { SURVIVAL_CONFIG } from '../src/survival/config.ts';
import { CAVE_BOUNDS, ROCK_SHELTERS } from '../src/survival/ShelterZones.ts';
import {
  GROVE_KEEPER,
  GROVE_LANDMARK,
  LAST_PREDICTOR,
  OBSERVATORY_LANDMARK,
  PIT_LANDMARK,
  PIT_REGISTRAR,
  SPAWN_HINT,
} from '../src/world/landmarks.ts';
import { GROVE_SITE, OBSERVATORY_SITE, PIT_SITE } from '../src/world/Terrain.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const outDir = path.join(root, 'export/unity-snapshot');

function gitSha(): string {
  try {
    return execSync('git rev-parse --short HEAD', { cwd: root, encoding: 'utf8' }).trim();
  } catch {
    return 'unknown';
  }
}

function writeJson(relative: string, data: unknown): void {
  const full = path.join(outDir, relative);
  mkdirSync(path.dirname(full), { recursive: true });
  writeFileSync(full, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}

const LOCALES: Locale[] = ['en', 'zh', 'ja'];

const logsByLocale: Record<string, unknown[]> = {};
for (const locale of LOCALES) {
  logsByLocale[locale] = TEXT_LOGS.map((log) => {
    const copy = getLogCopy(log, locale);
    return {
      id: log.id,
      title: copy.title,
      body: copy.body,
      position: log.position,
      interactionRadius: log.interactionRadius,
      requiresStableEra: log.requiresStableEra ?? false,
      requiresWorldStage: log.requiresWorldStage ?? 0,
    };
  });
}

mkdirSync(outDir, { recursive: true });

writeJson('manifest.json', {
  schemaVersion: 1,
  generatedAt: new Date().toISOString(),
  sourceRepo: 'lawrence-via-mk1987/3body',
  gitSha: gitSha(),
  webDemoUrl: 'https://lawrence-via-mk1987.github.io/3body/',
  docs: [
    'docs/GDD.md',
    'docs/ORBITAL_SIM.md',
    'docs/PATH_B_UNITY_PLAN.md',
    'docs/VISUAL_TARGET_FF8_UNITY_FORK.md',
  ],
  unityImportTarget: 'Assets/StreamingAssets/WebReference/',
});

writeJson('orbital_config.json', ORBITAL_CONFIG);
writeJson('survival_config.json', SURVIVAL_CONFIG);
writeJson('sky_palettes.json', SKY_PALETTES);
writeJson('phase_labels.json', PHASE_LABELS);

writeJson('landmarks.json', {
  pit: PIT_LANDMARK,
  grove: GROVE_LANDMARK,
  observatory: OBSERVATORY_LANDMARK,
  spawnHint: SPAWN_HINT,
  playerSpawn: { x: 0, y: 12, z: 24, yaw: Math.PI },
  pitRegistrar: PIT_REGISTRAR,
  lastPredictor: LAST_PREDICTOR,
  groveKeeper: GROVE_KEEPER,
  terrainSites: {
    pit: PIT_SITE,
    grove: GROVE_SITE,
    observatory: OBSERVATORY_SITE,
  },
});

writeJson('shelter_zones.json', {
  cave: CAVE_BOUNDS,
  rockShelters: ROCK_SHELTERS,
});

for (const locale of LOCALES) {
  writeJson(`logs/${locale}.json`, logsByLocale[locale]);
}

const docsOut = path.join(outDir, 'docs');
mkdirSync(docsOut, { recursive: true });
for (const doc of ['GDD.md', 'ORBITAL_SIM.md', 'PATH_B_UNITY_PLAN.md', 'VISUAL_TARGET_FF8_UNITY_FORK.md']) {
  const src = path.join(root, 'docs', doc);
  if (existsSync(src)) {
    cpSync(src, path.join(docsOut, doc));
  }
}

writeFileSync(
  path.join(outDir, 'README.md'),
  `# Unity content snapshot

Generated by \`npm run export:unity\` in the **3body** web repo.

Copy this folder into your Unity project:

\`\`\`text
Assets/StreamingAssets/WebReference/
\`\`\`

Or symlink for live iteration during U1.

## Files

| File | Use in Unity |
|------|----------------|
| \`manifest.json\` | Version / git SHA for parity checks |
| \`orbital_config.json\` | Load into \`OrbitalConfig\` ScriptableObject |
| \`sky_palettes.json\` | Phase volumes / fog / exposure |
| \`landmarks.json\` | Place greybox triggers & NPC talk radii |
| \`shelter_zones.json\` | Cave + rock shelter volumes |
| \`survival_config.json\` | Vitality / hydration tuning |
| \`logs/*.json\` | Log markers + localized copy |
| \`docs/\` | Reference GDD and orbital spec |

See \`unity/IMPORT_CONTENT_SNAPSHOT.md\` for Editor import steps.

**Do not hand-edit** generated JSON — change TypeScript sources and re-run export.
`,
  'utf8',
);

console.log(`Unity snapshot written to ${outDir}`);
